<a href="https://colab.research.google.com/github/amirmaruf030/DataMining/blob/main/Preprocessing_Data_Pengunjung.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('Data_pengunjung.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(x)

[['man' 19.0]
 ['girls' 18.0]
 ['man' nan]
 ['girls' 19.0]
 ['man' 19.0]
 ['man' 20.0]
 ['man' nan]
 ['girls' 19.0]
 ['man' 18.0]
 ['man' 20.0]]


In [8]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:2])
x[:, 1:2] = imputer.transform(x[:, 1:2])

In [10]:
print(x)

[['man' 19.0]
 ['girls' 18.0]
 ['man' 19.0]
 ['girls' 19.0]
 ['man' 19.0]
 ['man' 20.0]
 ['man' 19.0]
 ['girls' 19.0]
 ['man' 18.0]
 ['man' 20.0]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[0.0 1.0 19.0]
 [1.0 0.0 18.0]
 [0.0 1.0 19.0]
 [1.0 0.0 19.0]
 [0.0 1.0 19.0]
 [0.0 1.0 20.0]
 [0.0 1.0 19.0]
 [1.0 0.0 19.0]
 [0.0 1.0 18.0]
 [0.0 1.0 20.0]]


In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [16]:
print(x_train)

[[0.0 1.0 19.0]
 [0.0 1.0 19.0]
 [0.0 1.0 19.0]
 [1.0 0.0 19.0]
 [1.0 0.0 18.0]
 [1.0 0.0 19.0]
 [0.0 1.0 18.0]
 [0.0 1.0 20.0]]


In [17]:
print(x_test)

[[0.0 1.0 19.0]
 [0.0 1.0 20.0]]


In [18]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [19]:
print(y_test)

[0 1]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 2:] = sc.fit_transform(x_train[:, 2:])
x_test[:, 2:] = sc.transform(x_test[:, 2:])

In [21]:
print(x_train)

[[0.0 1.0 0.20851441405707477]
 [0.0 1.0 0.20851441405707477]
 [0.0 1.0 0.20851441405707477]
 [1.0 0.0 0.20851441405707477]
 [1.0 0.0 -1.4596008983995234]
 [1.0 0.0 0.20851441405707477]
 [0.0 1.0 -1.4596008983995234]
 [0.0 1.0 1.876629726513673]]


In [22]:
print(x_test)

[[0.0 1.0 0.20851441405707477]
 [0.0 1.0 1.876629726513673]]
